[colors.primary]
background = '#19120c'
foreground = '#efe0d6'

[colors.selection]
text = '#efe0d6'
background = '#6b3a05'

[colors.cursor]
text = '#19120c'
cursor = '#ffb77b'

[colors.normal]
black   = '#19120c'
red     = '#e2497f'
green   = '#97d66e'
yellow  = '#dbad7b'
blue    = '#bd6e2d'
magenta = '#bf9470'
cyan    = '#ffb77b'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f90'
green   = '#aae086'
yellow  = '#e8c197'
blue    = '#ffc791'
magenta = '#b36447'
cyan    = '#967243'
white   = '#ffffff'
