[colors.primary]
background = '#141218'
foreground = '#e6e0e9'

[colors.selection]
text = '#e6e0e9'
background = '#4d3d75'

[colors.cursor]
text = '#141218'
cursor = '#d0bcfe'

[colors.normal]
black   = '#141218'
red     = '#df5141'
green   = '#6ed675'
yellow  = '#dbd97b'
blue    = '#926ce2'
magenta = '#a296be'
cyan    = '#d0bcfe'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06a5f'
green   = '#86e08b'
yellow  = '#e8e697'
blue    = '#dfc9ff'
magenta = '#7d6acd'
cyan    = '#8a6ab4'
white   = '#ffffff'
