[colors.primary]
background = '#1a120d'
foreground = '#f0dfd7'

[colors.selection]
text = '#f0dfd7'
background = '#6f3812'

[colors.cursor]
text = '#1a120d'
cursor = '#ffb68c'

[colors.normal]
black   = '#1a120d'
red     = '#e24980'
green   = '#98d66e'
yellow  = '#dbac7b'
blue    = '#be6e40'
magenta = '#bf937a'
cyan    = '#ffb68c'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f91'
green   = '#aae086'
yellow  = '#e8c097'
blue    = '#ffc397'
magenta = '#b26452'
cyan    = '#97724f'
white   = '#ffffff'
