[colors.primary]
background = '#101418'
foreground = '#e0e2e8'

[colors.selection]
text = '#e0e2e8'
background = '#0f4a73'

[colors.cursor]
text = '#101418'
cursor = '#9bcbfb'

[colors.normal]
black   = '#101418'
red     = '#e64c48'
green   = '#72d66e'
yellow  = '#dbd07b'
blue    = '#4e85bd'
magenta = '#829fbc'
cyan    = '#9bcbfb'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f60'
green   = '#88e086'
yellow  = '#e8df97'
blue    = '#a6d9ff'
magenta = '#44809e'
cyan    = '#607aa7'
white   = '#ffffff'
